# Generated by Django 3.1.5 on 2026-04-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0002_auto_20260317_1851'),
        ('academic_information', '0002_auto_20260313_1303'),
    ]

    operations = [
    ]
