# Generated by Django 3.1.5 on 2026-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomvacationrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='roomvacationrequest',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='roomvacationrequest',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomvacationrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='roomvacationrequest',
            name='verified_by_caretaker',
        ),
        migrations.RenameField(
            model_name='hostelleave',
            old_name='remark',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hostelstudentattendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hostelfine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostelleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ExtendedStayRequest',
        ),
        migrations.DeleteModel(
            name='RoomVacationRequest',
        ),
    ]
