# Generated by Django 3.1.5 on 2026-04-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_merge_20260402_1331'),
        ('hostel_management', '0002_auto_20260413_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='RoomVacationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Clearance'), ('verified', 'Verified by Caretaker'), ('approved', 'Approved by Warden'), ('completed', 'Vacation Completed')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hallroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to='academic_information.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedStayApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hallroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_stays', to='academic_information.student')),
            ],
        ),
    ]
