# Generated by Django 3.1.5 on 2026-04-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0003_auto_20260413_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestroombooking',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='departure_time',
        ),
    ]
