# Generated by Django 3.1.5 on 2026-04-18 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_management', '0004_auto_20260413_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Mixed', 'Mixed')], default='Boys', max_length=10)),
                ('total_capacity', models.PositiveIntegerField()),
                ('floor_count', models.PositiveIntegerField(default=1)),
                ('room_config_json', models.JSONField(blank=True, default=dict, help_text='JSON config for auto-generating rooms. Schema: {"floors": [{"floor": 1, "rooms_per_floor": 20, "capacity_per_room": 2}]}')),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('UnderMaintenance', 'Under Maintenance')], default='Inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostel_management_hostel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelStaffAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Warden', 'Warden'), ('Caretaker', 'Caretaker')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='hostel_management.hostel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostel_management_hostelstaffassignment',
                'ordering': ['-is_active', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HostelAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('detail_json', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hostel_management.hostel')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostel_management_hostelauditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('UnderMaintenance', 'Under Maintenance')], default='Available', max_length=20)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_setup', to='hostel_management.hostel')),
            ],
            options={
                'db_table': 'hostel_management_room',
                'ordering': ['hostel', 'floor', 'room_number'],
                'unique_together': {('hostel', 'room_number')},
            },
        ),
    ]
