# Generated by Django 3.1.5 on 2026-04-19 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_information', '0003_merge_20260402_1331'),
        ('hostel_management', '0005_hostel_hostelauditlog_hostelstaffassignment_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationApplicationWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_hostel_type', models.CharField(choices=[('Boy', 'Boys'), ('Girl', 'Girls'), ('Mixed', 'Mixed/International')], max_length=10)),
                ('preferred_room_type', models.CharField(choices=[('single', 'Single Seater'), ('double', 'Double Seater'), ('triple', 'Triple Seater')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Allotted', 'Allotted'), ('NotAllotted', 'Not Allotted')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_requests', to='academic_information.student')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hostel_management.accommodationapplicationwindow')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('student', 'window')},
            },
        ),
        migrations.CreateModel(
            name='RoomAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_at', models.DateTimeField(auto_now_add=True)),
                ('vacated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allotted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotments_made', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='hostel_management.hostel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='hostel_management.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allotments', to='academic_information.student')),
            ],
            options={
                'db_table': 'hostel_management_roomallotment',
                'unique_together': {('student', 'is_active')},
            },
        ),
        migrations.DeleteModel(
            name='RoomAllocation',
        ),
    ]
