# Generated by Django 3.1.5 on 2026-04-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0006_auto_20260419_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='id',
        ),
        migrations.AddField(
            model_name='hostel',
            name='hall_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='rooms_setup', to='hostel_management.hostel', to_field='hall_id'),
        ),
        migrations.AlterField(
            model_name='roomallotment',
            name='hostel',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='allotments', to='hostel_management.hostel', to_field='hall_id'),
        ),
        migrations.AlterField(
            model_name='hostelstaffassignment',
            name='hostel',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='staff_assignments', to='hostel_management.hostel', to_field='hall_id'),
        ),
        migrations.AlterField(
            model_name='hostelauditlog',
            name='hostel',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='audit_logs', to='hostel_management.hostel', to_field='hall_id'),
        ),
    ]
