# Generated by Django 3.1.5 on 2026-04-20 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0008_fix_hostel_fk_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestroom',
            options={'ordering': ['hostel', 'room_number']},
        ),
        migrations.AlterModelOptions(
            name='hostelinventory',
            options={'ordering': ['hostel', 'item_name']},
        ),
        migrations.RenameField(
            model_name='hostelcomplaint',
            old_name='hall_name',
            new_name='hostel_name',
        ),
        migrations.RemoveField(
            model_name='extendedstayapplication',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hostelallotment',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hostelhistory',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hostelinventory',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hostelleave',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hostelnoticeboard',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hostelstudentattendance',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='hosteltransactionhistory',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='roomchangerequest',
            name='current_hall',
        ),
        migrations.RemoveField(
            model_name='roomchangerequest',
            name='requested_hall',
        ),
        migrations.RemoveField(
            model_name='roomvacationrequest',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='staffschedule',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='workerreport',
            name='hall',
        ),
        migrations.AddField(
            model_name='extendedstayapplication',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hostel'),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='guest_rooms', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='guest_bookings', to='hostel_management.hostel'),
        ),
        migrations.AddField(
            model_name='hostelallotment',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel_management.hostel'),
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelhistory',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelinventory',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelleave',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hostel_management.hostel'),
        ),
        migrations.AddField(
            model_name='hostelnoticeboard',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelstudentattendance',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hosteltransactionhistory',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomchangerequest',
            name='current_hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='room_change_from', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomchangerequest',
            name='requested_hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='room_change_to', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomvacationrequest',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerreport',
            name='hostel',
            field=models.ForeignKey(default='H-4', on_delete=django.db.models.deletion.CASCADE, related_name='worker_reports', to='hostel_management.hostel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodationrequest',
            name='preferred_hostel_type',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Mixed', 'Mixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='extendedstayapplication',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.room'),
        ),
        migrations.AlterField(
            model_name='roomallocationchange',
            name='current_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests_from', to='hostel_management.room'),
        ),
        migrations.AlterField(
            model_name='roomallocationchange',
            name='requested_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_to', to='hostel_management.room'),
        ),
        migrations.AlterField(
            model_name='roomchangerequest',
            name='current_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_change_from', to='hostel_management.room'),
        ),
        migrations.AlterField(
            model_name='roomchangerequest',
            name='requested_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_change_to', to='hostel_management.room'),
        ),
        migrations.AlterField(
            model_name='roomvacationrequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.room'),
        ),
        migrations.AlterUniqueTogether(
            name='guestroom',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.RemoveField(
            model_name='guestroom',
            name='hall',
        ),
    ]
