# Generated by Django 3.1.5 on 2026-04-20 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_merge_20260402_1331'),
        ('hostel_management', '0009_auto_20260420_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hostel_management.guestroom'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='rooms_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_room_bookings', to='academic_information.student'),
        ),
    ]
