# Generated by Django 3.1.5 on 2026-04-20 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_merge_20260402_1331'),
        ('hostel_management', '0010_auto_20260420_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedstayapplication',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hostel'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hostel_management.guestroom'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_bookings', to='hostel_management.hostel'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='rooms_required',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_room_bookings', to='academic_information.student'),
        ),
        migrations.AlterField(
            model_name='hostelcomplaint',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel_management.hostel'),
        ),
        migrations.AlterUniqueTogether(
            name='roomallotment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='roomallotment',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('student', 'is_active'), name='unique_active_allotment'),
        ),
    ]
