# Generated by Django 3.1.5 on 2026-04-20 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_merge_20260402_1331'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_management', '0011_auto_20260420_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('documents', models.FileField(blank=True, null=True, upload_to='hostel/leaves/docs/')),
                ('decision_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_leaves', to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hostel_management.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='academic_information.student')),
            ],
            options={
                'db_table': 'hostel_management_leaverequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('OnLeave', 'OnLeave'), ('NotMarked', 'NotMarked')], default='NotMarked', max_length=20)),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_entries', to='hostel_management.leaverequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic_information.student')),
            ],
            options={
                'db_table': 'hostel_management_studentattendancerecord',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.RemoveField(
            model_name='hostelstudentattendance',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='hostelstudentattendance',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='HostelLeave',
        ),
        migrations.DeleteModel(
            name='HostelStudentAttendance',
        ),
    ]
