# Generated by Django 3.1.5 on 2026-04-20 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_management', '0012_auto_20260420_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='escalated_to',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='escalated_to_warden',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='hostel_name',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='resolution_date',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='title',
        ),
        migrations.RemoveField(
            model_name='hostelcomplaint',
            name='warden_remarks',
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints_unified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='hostel/complaints/'),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='complaint_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hostelcomplaint',
            name='resolved_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostelcomplaint',
            name='category',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Cleaning', 'Cleaning'), ('Security', 'Security'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostelcomplaint',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('InProgress', 'In Progress'), ('Escalated', 'Escalated'), ('Resolved', 'Resolved')], default='Submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hostel_management.hostelcomplaint')),
            ],
            options={
                'db_table': 'hostel_management_complainthistory',
                'ordering': ['-timestamp'],
            },
        ),
    ]
