# Generated by Django 3.1.5 on 2026-04-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0013_auto_20260420_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelcomplaint',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('InProgress', 'In Progress'), ('Escalated', 'Escalated'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=20),
        ),
    ]
