# Generated by Django 3.1.5 on 2026-04-20 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0003_merge_20260402_1331'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_management', '0014_auto_20260420_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelfine',
            options={'ordering': ['-imposed_date']},
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='fine_type',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='waive_reason',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='waived_by',
        ),
        migrations.RemoveField(
            model_name='hostelfine',
            name='waived_date',
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='category',
            field=models.CharField(choices=[('HostelRuleViolation', 'Hostel Rule Violation'), ('PropertyDamage', 'Property Damage'), ('AttendanceViolation', 'Attendance Violation'), ('RoomStandardsViolation', 'Room Standards Violation')], default='HostelRuleViolation', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='hostel/fines/evidence/'),
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='fine_uid',
            field=models.CharField(default='TEMP-ID', max_length=24, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='imposed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fines_imposed', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='imposed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostelfine',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostelfine',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='academic_information.student'),
        ),
        migrations.AlterModelTable(
            name='hostelfine',
            table='hostel_management_hostelfine',
        ),
        migrations.CreateModel(
            name='FineExtraDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(max_length=50)),
                ('detail_json', models.JSONField()),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_details', to='hostel_management.hostelfine')),
            ],
            options={
                'db_table': 'hostel_management_fineextradetail',
            },
        ),
    ]
