# Generated by Django 3.1.5 on 2026-04-20 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_management', '0015_auto_20260420_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('New', 'New'), ('Replacement', 'Replacement'), ('Additional', 'Additional')], max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to='hostel_management.hostel')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_resource_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_resource_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostel_management_resourcerequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Cleaning', 'Cleaning'), ('Bedding', 'Bedding'), ('Equipment', 'Equipment'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Other', 'Other')], default='Other', max_length=50)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('expected_quantity', models.PositiveIntegerField(default=0)),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged'), ('Missing', 'Missing')], default='Good', max_length=20)),
                ('last_inspected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='hostel_management.hostel')),
            ],
            options={
                'db_table': 'hostel_management_inventoryitem',
                'ordering': ['hostel', 'category', 'name'],
                'unique_together': {('hostel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryDiscrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('Missing', 'Missing'), ('Damaged', 'Damaged'), ('Depleted', 'Depleted')], max_length=20)),
                ('expected_qty', models.PositiveIntegerField()),
                ('actual_qty', models.PositiveIntegerField()),
                ('remarks', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hostel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='hostel_management.inventoryitem')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_discrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostel_management_inventorydiscrepancy',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('new_qty', models.PositiveIntegerField()),
                ('old_condition', models.CharField(blank=True, max_length=20, null=True)),
                ('new_condition', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hostel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hostel_management.inventoryitem')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostel_management_inventoryauditlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
