# Generated by Django 3.1.5 on 2026-04-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0016_inventoryauditlog_inventorydiscrepancy_inventoryitem_resourcerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='category',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Cleaning', 'Cleaning'), ('Bedding', 'Bedding'), ('Equipment', 'Equipment'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
