# Generated by Django 3.1.5 on 2026-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0017_resourcerequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydiscrepancy',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged'), ('Missing', 'Missing')], default='Good', max_length=20),
        ),
    ]
