# Generated by Django 3.1.5 on 2026-04-20 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_information', '0003_merge_20260402_1331'),
        ('hostel_management', '0019_notice_noticereadstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestroom',
            options={'ordering': ['hostel', 'room__room_number']},
        ),
        migrations.AlterModelOptions(
            name='guestroombooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='guestroombooking',
            old_name='arrival_date',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='guestroombooking',
            old_name='departure_date',
            new_name='check_out_date',
        ),
        migrations.RenameField(
            model_name='guestroombooking',
            old_name='checked_in_at',
            new_name='id_verified_at',
        ),
        migrations.RenameField(
            model_name='guestroombooking',
            old_name='purpose',
            new_name='visit_purpose',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='checked_out_at',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='guest_address',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='guest_room',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='review_remarks',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='rooms_required',
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='total_guests',
        ),
        migrations.AddField(
            model_name='guestroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='room',
            field=models.OneToOneField(default=561, on_delete=django.db.models.deletion.CASCADE, related_name='guest_room_info', to='hostel_management.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='advance_charge_breakdown_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='booking_uid',
            field=models.CharField(default='TMP-MIG-ID', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='id_proof_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='per_night_rate',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='room',
            field=models.ForeignKey(default=561, on_delete=django.db.models.deletion.CASCADE, related_name='guest_bookings', to='hostel_management.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestroom',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_rooms_registry', to='hostel_management.hostel'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_room_bookings', to='hostel_management.hostel'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('CheckedIn', 'Checked In'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='student',
            field=models.ForeignKey(default='20BSM024', on_delete=django.db.models.deletion.CASCADE, related_name='guest_room_bookings', to='academic_information.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='guestroom',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='guestroom',
            table='hostel_management_guestroom',
        ),
        migrations.AlterModelTable(
            name='guestroombooking',
            table='hostel_management_guestroombooking',
        ),
        migrations.CreateModel(
            name='GuestRoomPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_night_rate', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('max_duration_nights', models.PositiveIntegerField(default=7)),
                ('min_advance_days', models.PositiveIntegerField(default=2)),
                ('max_advance_days', models.PositiveIntegerField(default=30)),
                ('max_concurrent_bookings_per_student', models.PositiveIntegerField(default=3)),
                ('fines_grace_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_policy', to='hostel_management.hostel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostel_management_guestroompolicy',
            },
        ),
        migrations.CreateModel(
            name='GuestRoomInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_found', models.BooleanField(default=False)),
                ('checklist_json', models.JSONField(default=dict)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('damage_photos', models.FileField(blank=True, null=True, upload_to='hostel/guest_rooms/damages/')),
                ('severity', models.CharField(blank=True, choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Severe', 'Severe')], max_length=20, null=True)),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inspection_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='hostel_management.guestroombooking')),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostel_management_guestroominspection',
            },
        ),
        migrations.RemoveField(
            model_name='guestroom',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='guestroom',
            name='occupied_till',
        ),
        migrations.RemoveField(
            model_name='guestroom',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='guestroom',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='guestroom',
            name='status',
        ),
        migrations.RemoveField(
            model_name='guestroom',
            name='updated_at',
        ),
    ]
