# Generated by Django 3.1.5 on 2026-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0020_auto_20260420_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestroombooking',
            name='guest_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
