# Generated by Django 3.1.5 on 2026-04-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0021_auto_20260420_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestroombooking',
            name='caretaker_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
