# Generated by Django 3.1.5 on 2026-04-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0022_guestroombooking_caretaker_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroominspection',
            name='severity',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Severe', 'Severe')], max_length=20, null=True),
        ),
    ]
