# Generated by Django 3.1.5 on 2026-04-21 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0024_guardshift_securityguard_shiftschedulelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_guards', to='hostel_management.hostel'),
        ),
    ]
