# Generated by Django 3.1.5 on 2026-04-21 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_management', '0026_auto_20260421_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityguard',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_guard_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel_management.securityguard'),
        ),
    ]
