# Generated by Django 3.1.5 on 2026-04-21 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_management', '0027_auto_20260421_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='waive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines_waived', to=settings.AUTH_USER_MODEL),
        ),
    ]
